debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.com.kittopmall: debug
    org.springframework.web.servlet: debug
    org.mybatis: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kittopmall
    username: hooney
    password: hooney1108!
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

mybatis:
  mapper-locations: classpath:mapper/*.xml


